name: Node.js

env:
  DEBUG: napi:*
  APP_NAME: timesimp
  MACOSX_DEPLOYMENT_TARGET: "10.13"

permissions:
  contents: write
  id-token: write

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "nodejs-*"
    paths:
      - nodejs/**
      - .github/workflows/nodejs.yml

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-13
            target: x86_64-apple-darwin
            build: npm run build -- --target x86_64-apple-darwin
          - host: windows-latest
            build: npm run build -- --target x86_64-pc-windows-msvc
            target: x86_64-pc-windows-msvc
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
            build: |
              rustup update
              npm run build -- --target x86_64-unknown-linux-gnu
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
            build: |
              rustup update
              npm run build -- --target x86_64-unknown-linux-musl
          - host: macos-latest
            target: aarch64-apple-darwin
            build: npm run build -- --target aarch64-apple-darwin
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
            build: |
              rustup update
              npm run build -- --target aarch64-unknown-linux-gnu
          - host: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            setup: |
              sudo apt-get update
              sudo apt-get install gcc-arm-linux-gnueabihf -y
            build: npm run build -- --target armv7-unknown-linux-gnueabihf
          - host: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
            build: npm run build -- --target armv7-unknown-linux-musleabihf
          - host: ubuntu-latest
            target: aarch64-linux-android
            build: npm run build -- --target aarch64-linux-android
          - host: ubuntu-latest
            target: armv7-linux-androideabi
            build: npm run build -- --target armv7-linux-androideabi
          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
            build: |-
              set -e &&
              rustup update
              rustup target add aarch64-unknown-linux-musl &&
              npm run build -- --target aarch64-unknown-linux-musl
          - host: windows-latest
            target: aarch64-pc-windows-msvc
            build: npm run build -- --target aarch64-pc-windows-msvc
          - host: ubuntu-latest
            target: riscv64gc-unknown-linux-gnu
            setup: |
              sudo apt-get update
              sudo apt-get install gcc-riscv64-linux-gnu -y
            build: npm run build -- --target riscv64gc-unknown-linux-gnu
    name: stable - ${{ matrix.settings.target }} - node@20
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        if: ${{ !matrix.settings.docker }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: nodejs/package-lock.json
      - name: Install
        if: ${{ !matrix.settings.docker }}
        run: |
          rustup toolchain install --profile minimal --no-self-update stable
          rustup default stable
          rustup target add ${{ matrix.settings.target }}
      - uses: Swatinem/rust-cache@v2
      - if: ${{ matrix.settings.target == 'armv7-unknown-linux-gnueabihf' || matrix.settings.target == 'armv7-unknown-linux-musleabihf' }}
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - name: Setup toolchain
        if: ${{ matrix.settings.setup }}
        working-directory: nodejs
        run: ${{ matrix.settings.setup }}
        shell: bash
      - name: Install dependencies
        working-directory: nodejs
        run: npm install
      - name: Build in docker
        if: ${{ matrix.settings.docker }}
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ matrix.settings.docker }}
          options: "--user 0:0 -v ${{ github.workspace }}/.cargo-cache/git/db:/usr/local/cargo/git/db -v ${{ github.workspace }}/.cargo/registry/cache:/usr/local/cargo/registry/cache -v ${{ github.workspace }}/.cargo/registry/index:/usr/local/cargo/registry/index -v ${{ github.workspace }}:/build -w /build/nodejs"
          run: ${{ matrix.settings.build }}
      - name: Build
        working-directory: nodejs
        run: ${{ matrix.settings.build }}
        if: ${{ !matrix.settings.docker }}
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: nodejs/${{ env.APP_NAME }}.*.node
          if-no-files-found: error
  test-native-binding:
    name: Test bindings on ${{ matrix.settings.host }} - node@${{ matrix.node }}
    needs:
      - build
      - universal-macOS
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-13
            target: universal-apple-darwin
          - host: macos-latest
            target: universal-apple-darwin
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - host: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - host: windows-latest
            target: x86_64-pc-windows-msvc
        node:
          - "18"
          - "20"
          - "22"
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: nodejs/package-lock.json
      - name: Install dependencies
        working-directory: nodejs
        run: npm install
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: nodejs
      - name: List packages
        working-directory: nodejs
        run: ls -R .
        shell: bash
      - name: Test bindings
        working-directory: nodejs
        run: npm run test
  test-musl-binding:
    name: Test bindings on ${{ matrix.settings.target }} - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        settings:
          - target: aarch64-unknown-linux-musl
            platform: arm64
            os: ubuntu-24.04-arm
          - target: x86_64-unknown-linux-musl
            platform: amd64
            os: ubuntu-latest
        node:
          - "18"
          - "20"
          - "22"
    runs-on: ${{ matrix.settings.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: nodejs
      - name: Setup and run tests
        uses: addnab/docker-run-action@v3
        with:
          image: node:${{ matrix.node }}-alpine
          options: "--platform linux/${{ matrix.settings.platform }} -v ${{ github.workspace }}:/build -w /build/nodejs"
          run: |
            npm install
            npm run test
  universal-macOS:
    name: Build universal macOS binary
    needs:
      - build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: nodejs/package-lock.json
      - name: Install dependencies
        working-directory: nodejs
        run: npm install
      - name: Download macOS x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: bindings-x86_64-apple-darwin
          path: nodejs/artifacts
      - name: Download macOS arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: bindings-aarch64-apple-darwin
          path: nodejs/artifacts
      - name: Combine binaries
        working-directory: nodejs
        run: npm run universal
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-universal-apple-darwin
          path: nodejs/${{ env.APP_NAME }}.*.node
          if-no-files-found: error
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - test-native-binding
      - test-musl-binding
      - universal-macOS
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: nodejs/package-lock.json
      - name: Install dependencies
        working-directory: nodejs
        run: npm install
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: nodejs/artifacts
      - name: Move artifacts
        working-directory: nodejs
        run: npm run artifacts
      - name: List packages
        working-directory: nodejs
        run: ls -R ./npm
      - name: Show package.json
        working-directory: nodejs
        run: cat package.json
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/nodejs-')
        working-directory: nodejs
        run: |
          npm config set provenance true
          npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
